default_language_version:
  python: 3.8.3

repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3 # should match Python version
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear==20.1.4
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
    - id: black
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
  hooks:
    - id: isort
