// Code generated by 'go run make.go'. DO NOT EDIT.

package info

import (
	"runtime"
	"strings"
)

func init() {
	Version = "0.99.0"
	GitCommit = "779a866d"
	GitBranch = "gbbr/hurray"
	BuildDate = "2019-01-16 15:59:57.699624 -0500 EST m=+0.011212050"
	GoVersion = strings.TrimPrefix(runtime.Version(), "go")
}
