// Code generated by 'go run make.go'. DO NOT EDIT.

package info

import (
	"runtime"
	"strings"
)

func init() {
	Version = "0.99.0"
	GitCommit = "cc5d7bb6"
	GitBranch = "gbbr/hurray"
	BuildDate = "2019-01-16 12:04:40.366984 -0500 EST m=+0.011782336"
	GoVersion = strings.TrimPrefix(runtime.Version(), "go")
}
